### PR TITLE
For SonarQube5.1 (refs #8)

### PR DESCRIPTION
**Pull request by monaka**

### CODE REVIEW

**Comment by monaka** [comment]
Note: Still have 404 error issue. Should apply some more patches.

**Comment by monaka** [comment]
404 error was caused by #23. Even though CI was failed, it is running on my SQ 5.4 instance.

**Comment by monaka** [comment]
Hmm... It should be fixed #22 before merging...

**Comment by designerferro** [comment]
Have you change the API calls to the new sonar version?

**Pull request closed without merging**
